#------------------------------------------------------------------------------
# Alfredo Renteria
# Makefile for Lab4
#
# make			makes runRealEstateApplication
# make clean	cleans up binaries
#------------------------------------------------------------------------------

runRealEstateApplication:
	gcc -o runRealEstateApplication runRealEstateApplication.c -I /usr/include/postgresql/ -lpq

clean:
	rm -f runRealEstateApplication *.o